### ISSUE TITLE
Where to find "app-vars.yml"?

### ISSUE THREAD

**Issue by pedromschmitt** [EmailThis/ansible-rails#1]
Hi! Great project! 
Thank you for sharing this. I'm eager to test.

I have a question: in step 2 says 
"Step 2. Configuration
Open app-vars.yml and change the following variables..."

But I can't find the `app-vars.yml ` file in the project.
Does it have another name?

**Comment by bharani91** [comment]
Hi, I've just added `app-vars.yml`.
Let me know if you run into any other issues. I'd be happy to help :)
