### ISSUE TITLE
Add swap configuration

### ISSUE THREAD

**Issue by xdmx** [EmailThis/ansible-rails#2]
Hey Bharani, first of all, thank you for doing and sharing this. I've been looking for some time to look into Ansible for deploying Rails apps and this will surely be useful :raised_hands: 

In the past I used a very rough `server.txt` file with all things to run on a new server (who didn't? :grin:), and one of the things I've always set is some small swap file & swappiness in order to allow the system to not crash when under heavy load for a short amount of time.

Do you think it'd be useful to add as an extra configuration?

You may also want to chime in in the recent [Rails discussion](https://discuss.rubyonrails.org/t/rails-deployments/74624/14) about deployments if you didn't see it yet.

**Comment by bharani91** [comment]
Hey @xdmx, thanks for pointing me to the Rails discussion. 

> In the past I used a very rough server.txt file with all things to run on a new server (who didn't? 😁)

Yes, I've deployed more side projects than I care to remember using a txt file with a list of commands :) 

Regarding your suggestion about adding a swap file, is [this](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04) what you mean? It seems that using a swap file with SSDs (like that provided by DigitalOcean or Vultr) is not advisable. If you can point me to any other resource that talks about the advantages of adding a swap file, I'll be happy to add this as an optional configuration.
