### ISSUE TITLE
Task freezes at "Update remote repository using SSH key"

### ISSUE THREAD

**Issue by kaka-ruto** [EmailThis/ansible-rails#3]
When deploying, everything works well until it reaches `TASK [ansistrano.deploy : ANSISTRANO | GIT | Update remote repository using SSH key]`, where it freezes for as long as it can without exiting, even with an error.

I have regenerated keys without passphrases and added them to my private repo under `deploy keys`.

I have also added the private keys to ssh-agent and added  this to my ansible.cfg

`[ssh_connection]
ssh_args = -o ForwardAgent=yes
`

It still won't work. please direct me? 

I am suspecting the issue to be that the remote host cannot pull my private repository because it doesn't have the private keys, but at this point I do not why the solutions above do not work. (haven't tried manually copying the keys)

PS: I have two keys, a `.pem` key for accessing the server, and an `id_rsa` private key with it's public key added to Github.

**Comment by bharani91** [comment]
I haven't been able to replicate this issue. It seems to me that this is an issue with Ansistrano.
Can you please open an issue [there](https://github.com/ansistrano/deploy)?

**Comment by kaka-ruto** [comment]
Thank you. I have opened it here https://github.com/ansistrano/deploy/issues/353

**Comment by bharani91** [comment]
Great! I am closing this issue. Feel free to open another issue if you run into any problems with Ansible Rails.
