### ISSUE TITLE
puma.service.j2 template gives wrong command line for stopping Puma

### ISSUE THREAD

**Issue by noahgibbs** [EmailThis/ansible-rails#4]
Hi! In puma.service.j2, there is the following line:

    ExecStop={{ rbenv_bundle }} exec puma -S {{ app_current_path }}/config/puma.rb

However, that will actually cause the puma config file to be overwritten by a Puma YML state file, and won't stop Puma.

You may have meant to *start* Puma with the -S parameter to create a state file, then use that state file to stop Puma later using pumactl? Here's what I'm currently using:

ExecStart={{ rbenv_bundle }} exec puma -C {{ app_shared_path }}/config/puma.rb --control-url unix://{{ puma_control_socket }} --control-token {{ puma_control_token }} -S {{ puma_state_file }}
ExecStop={{ rbenv_bundle }} exec pumactl -S {{ puma_state_file }} stop

Note that for this you'd need to define a Puma control socket and token and a statefile location (I make a new Ansistrano shared dir for it), plus I'm using a generated shared config/puma.rb. So you can't just drop this in. But this approach can work if you feel like using it, or you could do something simpler with killing the PID.

**Comment by bharani91** [comment]
Hi,

Thanks for pointing out this bug.

I'll read up more about puma and investigate this shortly. Do you think the following would work?
```
ExecStop={{ rbenv_bundle }} exec pumactl -F {{ app_current_path }}/config/puma.rb stop
```

**Comment by noahgibbs** [comment]
That works for me locally. So yes, that would probably work.

You may also want to document that whatever Rails app you clone should have a config/puma.rb in the docs.

**Comment by bharani91** [comment]
Thanks for the suggestion. I've added this information to the README.
