### ISSUE TITLE
vault_pass was not found

### ISSUE THREAD

**Issue by sibananda-nu** [EmailThis/ansible-rails#9]
Hi,

When I try to run the ansible with vagrant it says .vault_pass file was not found.
I am new to ansible can you please help with this.
![image](https://user-images.githubusercontent.com/63705810/90337933-876fdb80-e003-11ea-9bf0-b99e52d4e5fd.png)

Thanks

**Comment by bharani91** [comment]
Create a file called `.vault_pass` with the password for decrypting/encrypting your vault file.
Refer to step 3 here - https://github.com/EmailThis/ansible-rails#step-3-storing-sensitive-information

Let me know if you run into any other issues. I'd be happy to help.

**Comment by lulalala** [comment]
@bharani91 sorry for taking your time. When I tried to follow step 3 by calling `ansible-vault create group_vars/all/vault.yml`, it would also err with the same message

> ERROR! The vault password file /Users/foo/ansible-rails/.vault_pass was not found

Could you know if I have missed any crucial step? Thanks.

**Comment by fffx** [comment]
@lulalala  In my case, I need comment the line `vault_password_file = ./.vault_pass` in ansible-config file, then I can create a new valut, after that uncommet it.
